name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

   

    # SonarCloud Analysis
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      run: mvn sonar:sonar -Dsonar.projectKey=Nadir1109_FPplatform-backend -Dsonar.organization=nadir1109 -Dsonar.host.url=https://sonarcloud.io

    # Build dockerfile
    - name: build dockerfile
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/freelance-back-end:latest .

    # Push to docker-hub
    - name: login into docker-hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push to docker-hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/freelance-back-end:latest
